name: Python application

on:
  push:
    branches:
    - main-flow
  pull_request:
    branches:
    - main-flow

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -v
    # - name: Deploy to Heroku
    #   env:
    #     HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
    #     HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
    #   if: github.ref == 'refs/heads/main' && job.status == 'success'
    #   run: |
    #     git remofte add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
    #     git push heroku HEAD:main -f